// Generated 20.09.2018 18:11:03 by Hibernate Tools 4.3.1



/**
 * Cities generated by hbm2java
 */
public class Cities  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String countryCode;
     private String district;
     private int population;

    public Cities() {
    }

    public Cities(String name, String countryCode, String district, int population) {
       this.name = name;
       this.countryCode = countryCode;
       this.district = district;
       this.population = population;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public int getPopulation() {
        return this.population;
    }
    
    public void setPopulation(int population) {
        this.population = population;
    }




}


