// Generated 20.09.2018 18:11:03 by Hibernate Tools 4.3.1



/**
 * Countries generated by hbm2java
 */
public class Countries  implements java.io.Serializable {


     private String code;
     private String name;
     private String continent;
     private String region;
     private float surfaceArea;
     private Short independenceYear;
     private int population;
     private Float lifeExpectancy;
     private Float gnp;
     private Float gnpOld;
     private String localName;
     private String governmentForm;
     private String headOfState;
     private Cities capital;
     private String code2;

    public Countries() {
    }

	
    public Countries(String code, String name, String continent, String region, float surfaceArea, int population, String localName, String governmentForm, String code2) {
        this.code = code;
        this.name = name;
        this.continent = continent;
        this.region = region;
        this.surfaceArea = surfaceArea;
        this.population = population;
        this.localName = localName;
        this.governmentForm = governmentForm;
        this.code2 = code2;
    }
    public Countries(String code, String name, String continent, String region, float surfaceArea, Short independenceYear, int population, Float lifeExpectancy, Float gnp, Float gnpOld, String localName, String governmentForm, String headOfState, Cities capital, String code2) {
       this.code = code;
       this.name = name;
       this.continent = continent;
       this.region = region;
       this.surfaceArea = surfaceArea;
       this.independenceYear = independenceYear;
       this.population = population;
       this.lifeExpectancy = lifeExpectancy;
       this.gnp = gnp;
       this.gnpOld = gnpOld;
       this.localName = localName;
       this.governmentForm = governmentForm;
       this.headOfState = headOfState;
       this.capital = capital;
       this.code2 = code2;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getContinent() {
        return this.continent;
    }
    
    public void setContinent(String continent) {
        this.continent = continent;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public float getSurfaceArea() {
        return this.surfaceArea;
    }
    
    public void setSurfaceArea(float surfaceArea) {
        this.surfaceArea = surfaceArea;
    }
    public Short getIndependenceYear() {
        return this.independenceYear;
    }
    
    public void setIndependenceYear(Short independenceYear) {
        this.independenceYear = independenceYear;
    }
    public int getPopulation() {
        return this.population;
    }
    
    public void setPopulation(int population) {
        this.population = population;
    }
    public Float getLifeExpectancy() {
        return this.lifeExpectancy;
    }
    
    public void setLifeExpectancy(Float lifeExpectancy) {
        this.lifeExpectancy = lifeExpectancy;
    }
    public Float getGnp() {
        return this.gnp;
    }
    
    public void setGnp(Float gnp) {
        this.gnp = gnp;
    }
    public Float getGnpOld() {
        return this.gnpOld;
    }
    
    public void setGnpOld(Float gnpOld) {
        this.gnpOld = gnpOld;
    }
    public String getLocalName() {
        return this.localName;
    }
    
    public void setLocalName(String localName) {
        this.localName = localName;
    }
    public String getGovernmentForm() {
        return this.governmentForm;
    }
    
    public void setGovernmentForm(String governmentForm) {
        this.governmentForm = governmentForm;
    }
    public String getHeadOfState() {
        return this.headOfState;
    }
    
    public void setHeadOfState(String headOfState) {
        this.headOfState = headOfState;
    }
    public Cities getCapital() {
        return this.capital;
    }
    
    public void setCapital(Cities capital) {
        this.capital = capital;
    }
    public String getCode2() {
        return this.code2;
    }
    
    public void setCode2(String code2) {
        this.code2 = code2;
    }




}


